apiVersion: apps/v1
kind: Deployment
metadata:
  name: operatorsdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operatorsdk
  template:
    metadata:
      labels:
        name: operatorsdk
    spec:
      serviceAccountName: operatorsdk
      containers:
        - name: operatorsdk
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - operatorsdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operatorsdk"
