kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operatorsdk
subjects:
- kind: ServiceAccount
  name: operatorsdk
roleRef:
  kind: Role
  name: operatorsdk
  apiGroup: rbac.authorization.k8s.io
