# permissions to do edit lights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: light-editor-role
rules:
- apiGroups:
  - smarthome.loodse.io
  resources:
  - lights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smarthome.loodse.io
  resources:
  - lights/status
  verbs:
  - get
  - patch
  - update
