# permissions to do viewer lights.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: light-viewer-role
rules:
- apiGroups:
  - smarthome.loodse.io
  resources:
  - lights
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - smarthome.loodse.io
  resources:
  - lights/status
  verbs:
  - get
