
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - smarthome.loodse.io
  resources:
  - shutters
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - smarthome.loodse.io
  resources:
  - shutters/status
  verbs:
  - get
  - patch
  - update
